---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.25
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.36
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:


  - name: "nominal"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-2-gd931f07-histograms-noloosefilter/hf_main_variables_systematics_February23_sherpa_221_only_nominal/*Z_sherpa_221*.hists
    styles:
      color: [174, 199, 232]
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "#alpha_{s} up"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-2-gd931f07-histograms-noloosefilter/hf_main_variables_systematics_February23_sherpa_221_only_weight_WZ_alpha_s_up/*Z_sherpa_221*.hists
    styles:
      color: [255, 127, 14]
      linewidth: 2
      legendstyle: L
      drawstyle: Ehist
    stack it: false

  - name: "#alpha_{s} down"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-2-gd931f07-histograms-noloosefilter/hf_main_variables_systematics_February23_sherpa_221_only_weight_WZ_alpha_s_down/*Z_sherpa_221*.hists
    styles:
      color: [255, 187, 120]
      linewidth: 2
      linestyle: 3
      legendstyle: L
      drawstyle: Ehist
    stack it: false

  - name: "CT14nnlo"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-2-gd931f07-histograms-noloosefilter/hf_main_variables_systematics_February23_sherpa_221_only_weight_WZ_CT14nnlo/*Z_sherpa_221*.hists
    styles:
      color: [44, 160, 44]
      linewidth: 2
      legendstyle: L
      drawstyle: Ehist
    stack it: false


  - name: "MMHT2014nnlo"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-2-gd931f07-histograms-noloosefilter/hf_main_variables_systematics_February23_sherpa_221_only_weight_WZ_MMHT2014nnlo/*Z_sherpa_221*.hists
    styles:
      color: [152, 223, 138]
      linewidth: 2
      linestyle: 2
      legendstyle: L
      drawstyle: Ehist
    stack it: false

  - name: "NNPDF up"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-2-gd931f07-histograms-noloosefilter/hf_main_variables_systematics_February23_sherpa_221_only_weight_WZ_NNPDF_up/*Z_sherpa_221*.hists
    styles:
      color: [214, 39, 40]
      linewidth: 2
      legendstyle: L
      drawstyle: Ehist
    stack it: false

  - name: "NNPDF down"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-2-gd931f07-histograms-noloosefilter/hf_main_variables_systematics_February23_sherpa_221_only_weight_WZ_NNPDF_down/*Z_sherpa_221*.hists
    styles:
      color: [255, 152, 150]
      linewidth: 2
      linestyle: 2
      legendstyle: L
      drawstyle: Ehist
    stack it: false

# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 20
        label: "36.1 fb^{-1}"
      -
        x: 0.25
        y: 0.80
        font: 43
        size: 20
        label: "Z+jets systematics"
      -
        x: 0.25
        y: 0.76
        font: 43
        size: 20
        label: "0L, #geq4j, =2b, E_{T}^{miss}>200 GeV, #Delta#phi^{4j}_{min}>0.4"
    canvas:
      width: 800
      height: 600
      logy: true
      ndivisions: 510
    legend:
      numcolumns: 1
      topmargin: 0.02
      leftmargin: 0.45
      textsize: 20
      entrysep: 0.04
      entryheight: 0.005
    ratio range: [0, 2]
    ratio label: "Ratio w.r.t. Nominal"
    ratio ytitle size: 20
    ratio ytitle offset: 1.5

  paths:

    ##### leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4

    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/cutflow:
      xlabel: "Cutflow"
      ylabel: "Events"
      ymin: 1
      ymax: 1000000000
      plot tag: logy
      ratio: true 
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/jets_n:
      xmin: 4
      xmax: 10
      ymin: 1
      ymax: 100000
      ndivisions: 10
      ylabel: Events
      xlabel: "Number of jets"
      plot tag: logy
      ratio: true
      canvas:
        ndivisions: 10
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/bjets_n:
      xmin: 2
      xmax: 6
      ymin: 1
      ymax: 10000000
      ylabel: Events
      xlabel: "Number of b-tagged jets"
      plot tag: logy
      ratio: true 
      canvas:
        ndivisions: 5
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/pt_jet_1:
      xmin: 50
      xmax: 800
      ymin: 1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "p_{T,1} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/dphi_min:
      xmin: 0.
      xmax: 3
      ymin: 1
      ymax: 100000
      ylabel: Events
      xlabel: "#Delta#phi^{4j}_{min}"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/met:
      xmin: 200
      xmax: 1000
      ymin: 0.1
      ymax: 1000000
      rebin: 5
      ylabel: Events
      xlabel: "E_{T}^{miss} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/meff_4j:
      xmin: 400
      xmax: 1600
      ymin: 0.01
      ymax: 10000000
      rebin: 5
      ylabel: Events
      xlabel: "m_{eff}^{4j} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/m_bb:
      xmin: 20
      xmax: 600
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/m_non_bb:
      xmin: 20
      xmax: 600
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{qq} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/mCT_bb:
      xmin: 0
      xmax: 600
      ymin: 0.1
      ymax: 100000
      rebin: 2
      ylabel: Events
      xlabel: "m_{CT}^{bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nJetsGeq4_nBJetsEq2_metG200_dphiMinG0p4/mTb_min:
      xmin: 0
      xmax: 600
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{T}^{b,min} [GeV]"
      plot tag: logy
      ratio: true 
