---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.25
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.36
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:

  - name: data
    files:
       - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*period*.hists
    styles:
      legendstyle: p
      color: black
    do not scale me: true
    stack it: false

  - name: "t#bar{t}"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*ttbar*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "single top"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*singletop*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "t#bar{t}+X"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*topEW*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "W+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*W_sherpa_220*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "Z+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*Z_sherpa_220*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "diboson"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*diboson*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: dijet
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361020*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361021*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361022*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361023*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361024*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361025*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361026*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361027*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*361028*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  # # - name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 350, m_{#tilde{#chi}^{0}_{1}} = 0"
  # - name: "(350, 0)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*394329*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false

  #   #- name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 500, m_{#tilde{#chi}^{0}_{1}} = 0"
  # - name: "(500, 0)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*394338*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false


  # # - name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 550, m_{#tilde{#chi}^{0}_{1}} = 150"
  # - name: "(550, 150)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*394346*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false

  # # - name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 800, m_{#tilde{#chi}^{0}_{1}} = 0"
  # - name: "(800, 0)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_prw_January24_MET_incl_filter_pu/*394766*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  
# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 20
        label: "36.1 fb^{-1}"
      -
        x: 0.25
        y: 0.80
        font: 43
        size: 20
        label: "0L, #geq4j, #geq2b, E_{T}^{miss}>200 GeV"
    canvas:
      width: 800
      height: 600
      logy: true
      ndivisions: 510
    legend:
      numcolumns: 1
      topmargin: 0.02
      # leftmargin: 0.5
      # rightmargin: 0.7
      textsize: 16
      entrysep: 0.024
      entryheight: 0.005

  paths:

    ##### signalleptonveto_nJetsGeq4_nBJetsGeq2_metG200

    hists/signalleptonveto_nJetsGeq4_nBJetsGeq2_metG200/average_int_per_crossing:
      xlabel: "#LT#mu#GT"
      ylabel: "Events"
      xmin: 0
      xmax: 50
      ymin: 1
      ymax: 100000000000
      plot tag: logy
      ratio: true 
