---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.25
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.36
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:

  - name: data
    files:
       - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*period*.hists
    styles:
      legendstyle: p
      color: black
    do not scale me: true
    stack it: false

  - name: "t#bar{t}"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*ttbar*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "single top"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*singletop*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "t#bar{t}+X"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*topEW*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "W+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*W_sherpa_220*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "Z+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Z_sherpa_220*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "diboson"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*diboson*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: dijet
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*361021*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*361022*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*361023*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*361024*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*361025*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*361026*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*361027*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*361028*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_300p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_300p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 100"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_300p0_100p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 350, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_350p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 350, m_{#tilde{#chi^{0}_{1}}} = 100"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_350p0_100p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 400, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_400p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 450, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_450p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_500p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 100"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_500p0_100p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 600, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_Zjets_CR_VR_September27_HT_incl_filter/*Wh_600p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  
# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 20
        label: "36.1 fb^{-1}"
      -
        x: 0.25
        y: 0.79
        font: 43
        size: 20
        label: "CR_{2}^{Z+jets}"
      -
        x: 0.25
        y: 0.75
        font: 43
        size: 14
        label: "2L, #geq4#leq5j, =2b, E_{T,ZCR}^{miss}>250 GeV, m_{eff,ZCR}^{4j}>900 GeV, #Delta#phi_{min}^{4j}>0.4"
      -
        x: 0.25
        y: 0.71
        font: 43
        size: 14
        label: "p_{T}^{l1}>140 GeV, |m_{Z}-90| < 15 GeV, m^{bb}>200 GeV"
    canvas:
      width: 800
      height: 600
      logy: true
      ndivisions: 10
    legend:
      numcolumns: 1
      topmargin: 0.02
      # leftmargin: 0.5
      # rightmargin: 0.7
      textsize: 26
      entrysep: 0.04
      entryheight: 0.008

  paths:

    ##### optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200

    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/cutflow:
      xlabel: "Cutflow"
      ylabel: "Events"
      ymin: 1
      ymax: 100000
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/jets_n:
      xmin: 4
      xmax: 10
      ymin: 1
      ymax: 1000
      ndivisions: 10
      ylabel: Events
      xlabel: "Number of jets"
      plot tag: logy
      ratio: true 
      canvas:
        ndivisions: 10
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/bjets_n:
      xmin: 2
      xmax: 6
      ymin: 1
      ymax: 10000
      ylabel: Events
      xlabel: "Number of b-tagged jets"
      plot tag: logy
      ratio: true 
      canvas:
        ndivisions: 5
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/dphi_min:
      xmin: 0.
      xmax: 3
      ymin: 1
      rebin: 2
      ymax: 10000
      ylabel: Events
      xlabel: "#Delta#phi^{4j}_{min}"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/met:
      xmin: 200
      xmax: 500
      ymin: 0.01
      ymax: 1000000
      rebin: 5
      ylabel: Events
      xlabel: "E_{T}^{miss} [GeV]"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/mTb_min:
      xmin: 0
      xmax: 300
      ymin: 0.1
      ymax: 100000
      rebin: 2
      ylabel: Events
      xlabel: "m_{T}^{b,min} [GeV]"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/meff_4j:
      xmin: 800
      xmax: 1400
      ymin: 0.01
      ymax: 100000000
      rebin: 5
      ylabel: Events
      xlabel: "m_{eff}^{4j} [GeV]"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/m_bb:
      xmin: 20
      xmax: 600
      ymin: 0.1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "m^{bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/mCT_bb:
      xmin: 0
      xmax: 300
      ymin: 0.1
      ymax: 100000
      rebin: 2
      ylabel: Events
      xlabel: "m_{CT}^{bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/m_non_bb:
      xmin: 20
      xmax: 600
      ymin: 0.1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "m^{non-bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/pt_lep_1:
      xmin: 0
      xmax: 500
      ymin: 0.1
      ymax: 10000
      rebin: 5
      ylabel: Events
      xlabel: "p_{T}^{l1} [GeV]"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/ZCR_met:
      xmin: 200
      xmax: 500
      ymin: 0.01
      ymax: 1000000
      rebin: 5
      ylabel: Events
      xlabel: "E_{T,ZCR}^{miss} [GeV]"
      plot tag: logy
      ratio: true 
    hists/optimization_Wh_CR2_Zjets_2L_lep1PtG140_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_ZCRmetG250_ZCRmeffG900_ZmassG75L105_mbbG200/ZCR_meff_4j:
      xmin: 800
      xmax: 1400
      ymin: 0.01
      ymax: 100000000
      rebin: 5
      ylabel: Events
      xlabel: "m_{eff,ZCR}^{4j} [GeV]"
      plot tag: logy
      ratio: true 
