---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.25
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.36
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:

  - name: data
    files:
       - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*period*.hists
    styles:
      legendstyle: p
      color: black
    do not scale me: true
    stack it: false

  - name: "t#bar{t}"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*ttbar*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "single top"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*singletop*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "t#bar{t}+X"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*topEW*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "W+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*W_sherpa_220*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "Z+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Z_sherpa_220*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "diboson"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*diboson*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: dijet
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*361021*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*361022*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*361023*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*361024*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*361025*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*361026*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*361027*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*361028*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_300p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_300p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 100"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_300p0_100p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 350, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_350p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 350, m_{#tilde{#chi^{0}_{1}}} = 100"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_350p0_100p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 400, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_400p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 450, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_450p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_500p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 100"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_500p0_100p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 600, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_main_variables_dataMC_September14_HT_incl_filter/*Wh_600p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  
# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 20
        label: "0L, #geq4j, #geq2b, E_{T}^{miss}>200 GeV, #Delta#phi^{4j}_{min}>0.4"
      -
        x: 0.25
        y: 0.80
        font: 43
        size: 20
        label: "36.1 fb^{-1}"
    canvas:
      width: 800
      height: 600
      logy: true
      ndivisions: 10
    legend:
      numcolumns: 1
      topmargin: 0.02
      # leftmargin: 0.5
      # rightmargin: 0.7
      textsize: 26
      entrysep: 0.04
      entryheight: 0.008

  paths:

    ##### leptonveto_nBJetsGeq2_dphiMinG0p4

    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/cutflow:
      xlabel: "Cutflow"
      ylabel: "Events"
      ymin: 1
      ymax: 100000000000
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/jets_n:
      xmin: 4
      xmax: 10
      ymin: 1
      ymax: 1000000000
      ndivisions: 10
      ylabel: Events
      xlabel: "Number of jets"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/bjets_n:
      xmin: 2
      xmax: 6
      ymin: 1
      ymax: 10000000
      ylabel: Events
      # xlabel: "b-jet multiplicity (77% eff)"
      xlabel: "Number of b-tagged jets"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/bjets_n_60:
      xmin: 2
      xmax: 6
      ymin: 1
      ymax: 10000000
      ylabel: Events
      # xlabel: "b-jet multiplicity (60% eff)"
      xlabel: "Number of b-tagged jets (60% eff)"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/bjets_n_70:
      xmin: 2
      xmax: 6
      ymin: 1
      ymax: 10000000
      ylabel: Events
      # xlabel: "b-jet multiplicity (70% eff)"
      xlabel: "Number of b-tagged jets (70% eff)"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/bjets_n_85:
      xmin: 2
      xmax: 6
      ymin: 1
      ymax: 10000000
      ylabel: Events
      # xlabel: "b-jet multiplicity (85% eff)"
      xlabel: "Number of b-tagged jets (85% eff)"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/pt_jet_1:
      xmin: 50
      xmax: 1500
      ymin: 1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "p_{T,1} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/pt_jet_2:
      xmin: 50
      xmax: 1500
      ymin: 1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "p_{T,2} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/pt_jet_3:
      xmin: 50
      xmax: 600
      ymin: 1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "p_{T,3} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/pt_jet_4:
      xmin: 50
      xmax: 600
      ymin: 1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "p_{T,4} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/dphi_min:
      xmin: 0
      xmax: 3.14
      ymin: 0.01
      ymax: 100000000000000
      ylabel: Events
      # xlabel: "min_{i=1-4} #Delta#Phi(jet_{i}, E_{T}^{miss})"
      xlabel: "#Delta#phi^{4j}_{min}"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/dphi_1jet:
      xmin: 0
      xmax: 3.14
      ymin: 0.01
      ymax: 100000000000000
      ylabel: Events
      # xlabel: "#Delta#Phi(jet_{1}, E_{T}^{miss})"
      xlabel: "#Delta#phi^{1j}"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/dphi_sum4jet:
      xmin: 0
      xmax: 3.14
      ymin: 0.01
      ymax: 100000000000000
      ylabel: Events
      # xlabel: "#Delta#Phi(di-boson, E_{T}^{miss})"
      xlabel: "#Delta#phi^{#Sigma4j}"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/met:
      xmin: 200
      xmax: 1000
      ymin: 0.1
      ymax: 10000000
      rebin: 4
      ylabel: Events
      xlabel: "E_{T}^{miss} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/met_sig:
      xmin: 200
      xmax: 1000
      ymin: 0.1
      ymax: 10000000
      rebin: 4
      ylabel: Events
      xlabel: "E_{T}^{miss} / #sqrt{H_{T}} [GeV]^{1/2}"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mTb_min:
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{T}^{b,min} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mT2_qqbb_minv0:
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{T2}(m_{#chi^{0}_{1}}=0 GeV) [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mT2_qqbb_minv50:
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{T2}(m_{#chi^{0}_{1}}=50 GeV) [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mT2_qqbb_minv100:
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{T2}(m_{#chi^{0}_{1}}=100 GeV) [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mT2_qqbb_minv150:
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{T2}(m_{#chi^{0}_{1}}=150 GeV) [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/meff_4j:
      xmin: 300
      xmax: 2500
      ymin: 0.01
      ymax: 100000000
      rebin: 4
      ylabel: Events
      xlabel: "m_{eff}^{4j} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mT_4j:
      xmin: 0
      xmax: 2500
      ymin: 0.001
      ymax: 1000000000
      rebin: 4
      ylabel: Events
      xlabel: "m_{T}^{4j} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/m_2j:
      xmin: 0
      xmax: 2500
      ymin: 0.001
      ymax: 100000000
      rebin: 4
      ylabel: Events
      xlabel: "m^{2j} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mT_2j:
      xmin: 0
      xmax: 2500
      ymin: 0.001
      ymax: 100000000
      rebin: 4
      ylabel: Events
      xlabel: "m_{T}^{2j} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/m_bb:
      ymin: 0.1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "m^{bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mT_bb:
      ymin: 0.1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "m_{T}^{bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mCT_bb:
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{CT}^{bb} [MeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/m_non_bb:
      ymin: 0.1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "m^{non-bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mT_non_bb:
      ymin: 0.1
      ymax: 1000000
      rebin: 4
      ylabel: Events
      xlabel: "m_{T}^{non-bb} [GeV]"
      plot tag: logy
      ratio: true 
    hists/leptonveto_nBJetsGeq2_dphiMinG0p4/mCT_non_bb:
      ymin: 0.1
      ymax: 1000000
      rebin: 2
      ylabel: Events
      xlabel: "m_{CT}^{non-bb} [MeV]"
      plot tag: logy 
      ratio: true 
