---
# defines samples groups for the cutflows
# wildcards for file patterns are allowed
# NOTE indentation matters
#
# ex. 
# samples:
#   - name: dijets
#     files:
#       - *36102*.hists
#   - name: "t#bar{t}" 
#     files:
#       - *ttbar*.hists     
# 
samples:

  - name: "\\srthree cuts: dijet"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*361021*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*361022*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*361023*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*361024*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*361025*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*361026*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*361027*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*361028*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_dijet_detailed_cutflow.txt"

  - name: "\\srthree cuts: diboson"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*diboson*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_diboson_detailed_cutflow.txt"

  - name: "\\srthree cuts: VH"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*342284*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*342285*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_VH_detailed_cutflow.txt"

  - name: "\\srthree cuts: \\ttbar"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*ttbar*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_ttbar_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbar (inclusive, 410000) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*410000*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_ttbar_410000_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbar (600<HT<1000, 407009) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*407009*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_ttbar_407009_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbar (1000<HT<1500, 407010) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*407010*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_ttbar_407010_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbar (HT>1500, 407011) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*407011*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_ttbar_407011_detailed_cutflow.txt"

  - name: "\\srthree cuts: single-top"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*singletop*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_singletop_detailed_cutflow.txt"

  - name: "\\srthree cuts: \\ttbarX"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*topEW*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_topEW_detailed_cutflow.txt"

  - name: "\\srthree cuts: ttH"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*341177*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*341270*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*341271*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_ttH_detailed_cutflow.txt"

  - name: "\\srthree cuts: \\Wjets, Sherpa 2.2.0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*W_sherpa_220*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_W_sherpa_220_detailed_cutflow.txt"

  - name: "\\srthree cuts: \\Zjets, Sherpa 2.2.0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*Z_sherpa_220*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_Z_sherpa_220_detailed_cutflow.txt"

  - name: "\\srthree cuts: \\Wjets, Sherpa 2.2.1"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*W_sherpa_221*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_W_sherpa_221_detailed_cutflow.txt"

  - name: "\\srthree cuts: \\Zjets, Sherpa 2.2.1"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*Z_sherpa_221*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR3_Z_sherpa_221_detailed_cutflow.txt"

# specify the cutflow

cutflows:
  paths:
    hists/all/cutflow:
      label: "All events"
      order: 0
    hists/default/cutflow:
      label: "Preselection"
      order: 1
    hists/optimization_Wh_SR3_nJetsGeq4Leq5/cutflow:
      label: "$4 \\leq \\njet \\leq 5$"
      order: 2
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200/cutflow:
      label: "\\Etmiss>200\\gev"
      order: 3
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200_leptonveto/cutflow:
      label: "$0L$"
      order: 4
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200_leptonveto_nBJetsEq2/cutflow:
      label: "$\\nbjet = 2$"
      order: 5
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4/cutflow:
      label: "$\\dphimin>0.4$"
      order: 6
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG700/cutflow:
      label: "$\\meffj>700\\gev$"
      order: 7
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG700_mTbminG180/cutflow:
      label: "$\\mTbmin>180\\gev$"
      order: 8
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG700_mTbminG180_mCTbbG190/cutflow:
      label: "$\\mctbb>190\\gev$"
      order: 9
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG700_mTbminG180_mCTbbG190_mbbG105L135/cutflow:
      label: "$105<\\mbb/\\gev<135$"
      order: 10
    hists/optimization_Wh_SR3_nJetsGeq4Leq5_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG700_mTbminG180_mCTbbG190_mbbG105L135_mNonbbG75L90/cutflow:
      label: "$75<\\mnonbb/\\gev<90$"
      order: 11
