---
# defines background groups for the cutflows
# wildcards for file patterns are allowed
# NOTE indentation matters
#
# ex. 
# backgrounds:
#   - name: dijets
#     files:
#       - *36102*.hists
#   - name: "t#bar{t}" 
#     files:
#       - *ttbar*.hists     
# 
backgrounds:

  - name: "dijet"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*361021*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*361022*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*361023*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*361024*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*361025*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*361026*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*361027*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*361028*.hists

  - name: "diboson"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*diboson*.hists

  - name: "$t\\bar{t}$"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*ttbar*.hists

  - name: "single-top"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*singletop*.hists

  # - name: "single-top (Wt incl top)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*410013*singletop*.hists
  # - name: "single-top (Wt incl antitop)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*410014*singletop*.hists
  # - name: "single-top (Wt $H_{T}>500~{\\rm GeV}$ top)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*407018*singletop*.hists
  # - name: "single-top (Wt $H_{T}>500~{\\rm GeV}$ antitop)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*407020*singletop*.hists
  # - name: "single-top (t-chan lept top)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*410011*singletop*.hists
  # - name: "single-top (t-chan lept antitop)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*410012*singletop*.hists
  # - name: "single-top (s-chan noAllHad top)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*410025*singletop*.hists
  # - name: "single-top (s-chan noAllHad antitop)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*410026*singletop*.hists

  - name: "$t\\bar{t}+X$"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*topEW*.hists

  - name: "$W$+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*W_sherpa_220*.hists

  - name: "$Z$+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*Z_sherpa_220*.hists

# defined analogously for signal samples
# one group per signal sample is required
signals:

  - name: "(300, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100001*300p0_0p0*.hists
  - name: "(300, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100002*300p0_50p0*.hists
  - name: "(300, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100003*300p0_100p0*.hists
  - name: "(350, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100004*350p0_0p0*.hists
  - name: "(350, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100005*350p0_50p0*.hists
  - name: "(350, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100006*350p0_100p0*.hists
  - name: "(400, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100007*400p0_0p0*.hists
  - name: "(400, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100008*400p0_50p0*.hists
  - name: "(400, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100009*400p0_100p0*.hists
  - name: "(450, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100010*450p0_0p0*.hists
  - name: "(450, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100011*450p0_50p0*.hists
  - name: "(450, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100012*450p0_100p0*.hists
  - name: "(450, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100013*450p0_150p0*.hists
  - name: "(500, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100014*500p0_0p0*.hists
  - name: "(500, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100015*500p0_50p0*.hists
  - name: "(500, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100016*500p0_100p0*.hists
  - name: "(500, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100017*500p0_150p0*.hists
  - name: "(500, 200)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100018*500p0_200p0*.hists
  - name: "(550, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100019*550p0_0p0*.hists
  - name: "(550, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100020*550p0_50p0*.hists
  - name: "(550, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100021*550p0_100p0*.hists
  - name: "(550, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100022*550p0_150p0*.hists
  - name: "(550, 200)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100023*550p0_200p0*.hists
  - name: "(600, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100024*600p0_0p0*.hists
  - name: "(600, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100025*600p0_50p0*.hists
  - name: "(600, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100026*600p0_100p0*.hists
  - name: "(600, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100027*600p0_150p0*.hists
  - name: "(700, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100028*700p0_0p0*.hists
  - name: "(700, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter/*100029*700p0_50p0*.hists

# specify the path to each cutflow histogram
# one cutflow will be saved for each path
cutflows:
  paths:
    hists/optimization_Wh_SR1_leptonveto_nJetsEq4_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG900_mTbMinG100_mCTbbG140/cutflow:
      outfile: "cutflow_resolved/cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter_HT_incl_filter/optimization_Wh_SR1_leptonveto_nJetsEq4_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG900_mTbMinG100_mCTbbG140.txt"
      caption: "Cutflow for SR1. Selections: $0L$, $\\njet = 4$, $\\nbjet = 2$, $\\dphimin > 0.4$, $\\Etmiss > 200 \\gev$, $\\meffj > 900\\gev$, $\\mctbb > 140\\gev$, $\\mTbmin > 100\\gev$, $105 < \\mbb/\\gev < 135$, $75 < \\mnonbb/\\gev < 105$."

    hists/optimization_Wh_CR1_ttbar_leptonveto_nJetsEq4_nBJetsEq2_mbbG135_mNonbbG75L90_metG200_meffG900_mTbMinL140_mCTbbL140/cutflow:
      outfile: "cutflow_resolved/cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter_HT_incl_filter/optimization_Wh_CR1_ttbar_leptonveto_nJetsEq4_nBJetsEq2_mbbG135_mNonbbG75L90_metG200_meffG900_mTbMinL140_mCTbbL140.txt"
      caption: "Cutflow for CR1$_{t\\bar{t}}$. Selections: $0L$, $\\njet = 4$, $\\nbjet = 2$, $\\Etmiss > 200 \\gev$, $\\meffj > 900\\gev$, $\\mctbb < 140\\gev$, $\\mTbmin < 140\\gev$, $1\\mbb/\\gev > 135$, $75 < \\mnonbb/\\gev < 105$."

    hists/optimization_Wh_SR2_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG250_meffG900_mTbMinG160_mCTbbG140/cutflow:
      outfile: "cutflow_resolved/cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter_HT_incl_filter/optimization_Wh_SR2_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG250_meffG900_mTbMinG160_mCTbbG140.txt"
      caption: "Cutflow for SR2. Selections: $0L$, $4 \\leq \\njet \\leq 5$, $\\nbjet = 2$, $\\dphimin > 0.4$, $\\Etmiss > 250 \\gev$, $\\meffj > 900\\gev$, $\\mctbb > 140\\gev$, $\\mTbmin > 160\\gev$, $105 < \\mbb/\\gev < 135$, $75 < \\mnonbb/\\gev < 105$."

    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbMinG180_mCTbbG190/cutflow:
      outfile: "cutflow_resolved/cutflow_Wh_SR_CR_VR_minimal_September15_HT_incl_filter_HT_incl_filter/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbMinG180_mCTbbG190.txt"
      caption: "Cutflow for SR3 -- ''low-$\\meffj$''. Selections: $0L$, $4 \\leq \\njet \\leq 5$, $\\nbjet = 2$, $\\dphimin > 0.4$, $\\Etmiss > 200 \\gev$, $\\meffj > 700\\gev$, $\\mctbb > 190\\gev$, $\\mTbmin > 180\\gev$, $105 < \\mbb/\\gev < 135$, $75 < \\mnonbb/\\gev < 105$."
