---
# defines samples groups for the cutflows
# wildcards for file patterns are allowed
# NOTE indentation matters
#
# ex. 
# samples:
#   - name: dijets
#     files:
#       - *36102*.hists
#   - name: "t#bar{t}" 
#     files:
#       - *ttbar*.hists     
# 
groups:

  - name: "Total Background"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_20180920_MET_incl_filter/*ttbar*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_20180920_MET_incl_filter/*singletop*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_20180920_MET_incl_filter/*W_sherpa_220*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_20180920_MET_incl_filter/*Z_sherpa_220*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_20180920_MET_incl_filter/*diboson*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_20180920_MET_incl_filter/*topEW*.hists
    outfile: "cutflow_resolved/cutflow_summary_bkgd_20180920.txt"
    caption: "Event selection cutflow for $0lbb$. Only statistical uncertainties are shown."
    label: "table:cutflow-0lbb-summary"

  - name: "Wh(550, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_20180920_MET_incl_filter/*394343*.hists
    outfile: "cutflow_resolved/cutflow_summary_550_0_20180920.txt"
    caption: "Event selection cutflow for $0lbb$. Only statistical uncertainties are shown."
    label: "table:cutflow-0lbb-summary"

  - name: "Wh(700, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_20180920_MET_incl_filter/*394357*.hists
    outfile: "cutflow_resolved/cutflow_summary_700_0_20180920.txt"
    caption: "Event selection cutflow for $0lbb$. Only statistical uncertainties are shown."
    label: "table:cutflow-0lbb-summary"

# specify the path to each cutflow histogram
# one cutflow will be saved for each path
#

cutflows:
  paths:
    hists/all/cutflow:
      label: "All events"
      order: 0
    hists/default/cutflow:
      label: "Preselection+Cleaning"
      order: 1
    hists/Wh_leptonveto/cutflow:
      label: "\\nlep=0"
      order: 2
    hists/Wh_leptonveto_nJetsGeq4Leq5/cutflow:
      label: "\\njet ($\\pt>30~\\GeV$) $\\in[4,~5]$"
      order: 3
    hists/Wh_leptonveto_nJetsGeq4Leq5_nBJetsEq2/cutflow:
      label: "\\nbjet=2"
      order: 4
    hists/Wh_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4/cutflow:
      label: "\\dphimin>0.4"
      order: 5
    hists/Wh_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG200/cutflow:
      label: "$\\met>200~\\GeV$"
      order: 6
    hists/Wh_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG200_meffG700/cutflow:
      label: "$\\meff>700~\\GeV$"
      order: 7
    hists/Wh_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG200_meffG700_mbbG105L135/cutflow:
      label: "$\\mbb\\in[105,135]~\\GeV$"
      order: 8
    hists/Wh_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG200_meffG700_mbbG105L135_mNonbbG75L90/cutflow:
      label: "$\\mnonbb\\in[75,90]~\\GeV$"
      order: 9
    
    ## TYPO IN NAME, SHOULD BE SR3 (cuts are correct though)
    hists/Wh_SR2_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG200_meffG700_mbbG105L135_mNonbbG75L90_mCTbbG190/cutflow:
      label: "\\mct>190~\\GeV$"
      order: 10
    hists/Wh_SR2_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG200_meffG700_mbbG105L135_mNonbbG75L90_mCTbbG190_mTbminG180/cutflow:
      label: "\\mTbmin>180~\\GeV$"
      order: 11 

    hists/Wh_SR2_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG250_meffG700_mbbG105L135_mNonbbG75L90/cutflow:
      label: "$\\met>250~\\GeV$"
      order: 12 
    hists/Wh_SR2_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG250_meffG900_mbbG105L135_mNonbbG75L90/cutflow:
      label: "$\\meff>900~\\GeV$"
      order: 13 
    hists/Wh_SR2_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG250_meffG900_mbbG105L135_mNonbbG75L90_mCTbbG140/cutflow:
      label: "\\mct>140~\\GeV$"
      order: 14 
    hists/Wh_SR2_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_metG250_meffG900_mbbG105L135_mNonbbG75L90_mCTbbG140_mTbminG160/cutflow:
      label: "\\mTbmin>160~\\GeV$"
      order: 15 
