---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.25
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.36
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:

  - name: "t#bar{t}"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*ttbar*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "single top"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*singletop*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "t#bar{t}+X"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*topEW*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "W+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*W_sherpa_220*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "Z+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*Z_sherpa_220*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "diboson"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*diboson*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  # - name: dijet
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*361021*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*361022*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*361023*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*361024*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*361025*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*361026*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*361027*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*361028*.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true

  # - name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 350, m_{#tilde{#chi}^{0}_{1}} = 0"
  - name: "(350, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*Wh_350p0_0p0.394329*.hists
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false

  #- name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 500, m_{#tilde{#chi}^{0}_{1}} = 0"
  - name: "(500, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*Wh_500p0_0p0.394338*.hists
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false

  #- name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 500, m_{#tilde{#chi}^{0}_{1}} = 150"
  - name: "(550, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*Wh_550p0_150p0.394346*.hists
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false

  # # - name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 650, m_{#tilde{#chi}^{0}_{1}} = 0"
  # - name: "(650, 0)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*Wh_650p0_0p0.394353*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # # - name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 650, m_{#tilde{#chi}^{0}_{1}} = 150"
  # - name: "(650, 150)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*Wh_650p0_150p0.394356*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false

  # - name: "m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}} = 800, m_{#tilde{#chi}^{0}_{1}} = 0"
  - name: "(800, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms/hf_Nm1_SR3_December14_MET_incl_filter/*Wh_800p0_0p0.394766*.hists
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false
  
# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 20
        label: "36.1 fb^{-1}"
      - 
        x: 0.25
        y: 0.80
        font: 43
        size: 20
        label: "SR3"
      - 
        x: 0.56
        y: 0.74
        font: 43
        size: 14
        label: "(m_{#tilde{#chi}^{#pm}_{1},#tilde{#chi}^{0}_{2}}, m_{#tilde{#chi}^{0}_{1}}) [GeV]"
    canvas:
      width: 800
      height: 600
      logy: true
      ndivisions: 10
      # ratio range: [0, 10]
      # ratio ndivisions: 2
    legend:
      numcolumns: 2
      topmargin: 0.02
      leftmargin: 0.35
      # rightmargin: 0.8
      textsize: 18
      entrysep: 0.012
      entryheight: 0.006

  paths:

    ## SR3 

    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/cutflow:
      xlabel: "Cutflow"
      ylabel: "Events"
      ymin: 0.01
      ymax: 200
      plot tag: logy
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/jets_n:
      xmin: 4
      xmax: 10
      ymin: 0.01
      ymax: 200
      ndivisions: 10
      ylabel: Events
      xlabel: "Number of jets"
      plot tag: logy
      canvas:
        ndivisions: 10
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/bjets_n:
      xmin: 2
      xmax: 6
      ymin: 0.01
      ymax: 200
      ylabel: Events
      xlabel: "Number of b-tagged jets"
      plot tag: logy
      canvas:
        ndivisions: 5
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/dphi_min:
      xmin: 0.
      xmax: 3
      ymin: 0.01
      rebin: 2
      ymax: 200
      ylabel: Events
      xlabel: "#Delta#phi^{4j}_{min}"
      plot tag: logy
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/met:
      xmin: 200
      xmax: 500
      ymin: 0.01
      ymax: 200
      rebin: 5
      ylabel: Events
      xlabel: "E_{T}^{miss} [GeV]"
      plot tag: logy
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/meff_4j:
      xmin: 600
      xmax: 1400
      ymin: 0.01
      ymax: 200
      rebin: 5
      ylabel: Events
      xlabel: "m_{eff}^{4j} [GeV]"
      plot tag: logy
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/mCT_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{CT}^{bb} [GeV]"
      plot tag: logy
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/mTb_min:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{T}^{b,min} [GeV]"
      plot tag: logy
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/m_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{bb} [GeV]"
      plot tag: logy
    hists/optimization_Wh_SR3_leptonveto_nJetsGeq4Leq5_nBJetsEq2_dphiMinG0p4_mbbG105L135_mNonbbG75L90_metG200_meffG700_mTbminG180_mCTbbG190/m_non_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{qq} [GeV]"
      plot tag: logy

    ## N-1
    hists/optimization_Wh_SR3_Nm1_nJets/jets_n:
      xmin: 4
      xmax: 10
      ymin: 0.01
      ymax: 200
      ndivisions: 10
      ylabel: Events
      xlabel: "Number of jets"
      plot tag: logy
      canvas:
        ndivisions: 10
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: N_{jet}"
    hists/optimization_Wh_SR3_Nm1_nBJets/bjets_n:
      xmin: 2
      xmax: 6
      ymin: 0.01
      ymax: 200
      ylabel: Events
      xlabel: "Number of b-tagged jets"
      plot tag: logy
      canvas:
        ndivisions: 5
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: N_{b-jet}"
    hists/optimization_Wh_SR3_Nm1_dphiMin/dphi_min:
      xmin: 0.
      xmax: 3
      ymin: 0.01
      rebin: 2
      ymax: 200
      ylabel: Events
      xlabel: "#Delta#phi^{4j}_{min}"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: #Delta#phi^{4j}_{min}"
    hists/optimization_Wh_SR3_Nm1_meff/meff_4j:
      xmin: 600
      xmax: 1400
      ymin: 0.01
      ymax: 200
      rebin: 5
      ylabel: Events
      xlabel: "m_{eff}^{4j} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: m_{eff}^{4j}"
    hists/optimization_Wh_SR3_Nm1_mCTbb/mCT_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{CT}^{bb} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: m_{CT}^{bb}"
    hists/optimization_Wh_SR3_Nm1_mTbmin/mTb_min:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{T}^{b,min} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: m_{T}^{b,min}"
    hists/optimization_Wh_SR3_Nm1_mbb/m_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 5000
      rebin: 2
      ylabel: Events
      xlabel: "m_{bb} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: m_{bb}"
    hists/optimization_Wh_SR3_Nm1_mNonbb/m_non_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 5000
      rebin: 2
      ylabel: Events
      xlabel: "m_{qq} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: m_{qq}"
    hists/optimization_Wh_SR3_Nm2_mbb_mNonbb/m_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 5000
      rebin: 2
      ylabel: Events
      xlabel: "m_{bb} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-2: m_{bb}, m_{qq}"
    hists/optimization_Wh_SR3_Nm2_mbb_mNonbb/m_non_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 5000
      rebin: 2
      ylabel: Events
      xlabel: "m_{qq} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-2: m_{bb}, m_{qq}"
 
    ## Removing lepton veto

    hists/optimization_Wh_SR3_Nm1_leptonveto/cutflow:
      xlabel: "Cutflow"
      ylabel: "Events"
      ymin: 0.01
      ymax: 200
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/jets_n:
      xmin: 4
      xmax: 10
      ymin: 0.01
      ymax: 200
      ndivisions: 10
      ylabel: Events
      xlabel: "Number of jets"
      plot tag: logy
      canvas:
        ndivisions: 10
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/bjets_n:
      xmin: 2
      xmax: 6
      ymin: 0.01
      ymax: 200
      ylabel: Events
      xlabel: "Number of b-tagged jets"
      plot tag: logy
      canvas:
        ndivisions: 5
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/dphi_min:
      xmin: 0.
      xmax: 3
      ymin: 0.01
      rebin: 2
      ymax: 200
      ylabel: Events
      xlabel: "#Delta#phi^{4j}_{min}"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/met:
      xmin: 200
      xmax: 500
      ymin: 0.01
      ymax: 200
      rebin: 5
      ylabel: Events
      xlabel: "E_{T}^{miss} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/meff_4j:
      xmin: 600
      xmax: 1400
      ymin: 0.01
      ymax: 200
      rebin: 5
      ylabel: Events
      xlabel: "m_{eff}^{4j} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/mCT_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{CT}^{bb} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/mTb_min:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{T}^{b,min} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/m_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{bb} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
    hists/optimization_Wh_SR3_Nm1_leptonveto/m_non_bb:
      xmin: 0
      xmax: 600
      ymin: 0.01
      ymax: 200
      rebin: 4
      ylabel: Events
      xlabel: "m_{qq} [GeV]"
      plot tag: logy
      texts:
        - 
          x: 0.25
          y: 0.76
          font: 43
          size: 18
          label: "N-1: Removing lepton-veto"
