---
# defines samples groups for the cutflows
# wildcards for file patterns are allowed
# NOTE indentation matters
#
# ex. 
# samples:
#   - name: dijets
#     files:
#       - *36102*.hists
#   - name: "t#bar{t}" 
#     files:
#       - *ttbar*.hists     
# 
samples:

  - name: "\\srone cuts: dijet"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*361021*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*361022*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*361023*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*361024*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*361025*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*361026*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*361027*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*361028*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_dijet_cutflow.txt"

  - name: "\\srone cuts: diboson"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*diboson*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.33-5-0-52-g169a7c2-mCTbb-MEV-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*342284*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.33-5-0-52-g169a7c2-mCTbb-MEV-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*342285*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_diboson_cutflow.txt"

  - name: "\\srone cuts: VH"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.33-5-0-52-g169a7c2-mCTbb-MEV-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*342284*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.33-5-0-52-g169a7c2-mCTbb-MEV-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*342285*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_VH_cutflow.txt"

  - name: "\\srone cuts: \\ttbar"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*ttbar*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_ttbar_detailed_cutflow.txt"

  - name: "\\srone cuts: single-top"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*singletop*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_singletop_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbarX"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*topEW*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_topEW_detailed_cutflow.txt"

  - name: "\\srone cuts: ttH"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*341177*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*341270*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*341271*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_ttH_cutflow.txt"

  - name: "\\srone cuts: \\Wjets, Sherpa 2.2.0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*W_sherpa_220*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_W_sherpa_220_detailed_cutflow.txt"

  - name: "\\srone cuts: \\Zjets, Sherpa 2.2.0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*Z_sherpa_220*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows/bkgd_SR1_Z_sherpa_220_detailed_cutflow.txt"

# specify the cutflow

cutflows:
  paths:
    hists/all/cutflow:
      label: "All events"
      order: 0
    hists/default/cutflow:
      label: "Preselection"
      order: 1
    hists/optimization_Wh_SR1_nJetsEq4/cutflow:
      label: "$\\njet = 4$"
      order: 2
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200/cutflow:
      label: "\\Etmiss>200\\gev"
      order: 3
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto/cutflow:
      label: "$0L$"
      order: 4
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2/cutflow:
      label: "$\\nbjet = 2$"
      order: 5
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4/cutflow:
      label: "$\\dphimin>0.4$"
      order: 6
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900/cutflow:
      label: "$\\meffj>900\\gev$"
      order: 7
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140/cutflow:
      label: "$\\mTbmin>140\\gev$"
      order: 8
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140/cutflow:
      label: "$\\mctbb>140\\gev$"
      order: 9
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140_mbbG105L135/cutflow:
      label: "$105<\\mbb/\\gev<135$"
      order: 10
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140_mbbG105L135_mNonbbG75L90/cutflow:
      label: "$75<\\mnonbb/\\gev<90$"
      order: 11
