---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.25
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.36
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:


  - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 0 (private JOs, jet-filter)"
    files:
      - /Users/joakim/ewk/truth_studies/simpleanalysis/Wh_500p0_0p0_100014_private.root
    styles:
      legendstyle: L
      drawstyle: E
      linewidth: 2
    stack it: false

  - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 0 (official JOs)"
    files:
      - /Users/joakim/ewk/truth_studies/simpleanalysis/Wh_500p0_0p0_394338_official.root
    styles:
      legendstyle: L
      drawstyle: E
      linewidth: 2
    stack it: false

  - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 0 (official JOs, jet-filter)"
    files:
      - /Users/joakim/ewk/truth_studies/simpleanalysis/Wh_500p0_0p0_10394338_official_test.root
    styles:
      legendstyle: L
      drawstyle: E
      linewidth: 2
    stack it: false

  
# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 20
        label: "36.1 fb^{-1}"
      - 
        x: 0.25
        y: 0.79
        font: 43
        size: 20
        label: "0L, #geq4j, E_{T}^{miss}>200 GeV"

    canvas:
      width: 800
      height: 600
      logy: true
      ndivisions: 10
    legend:
      numcolumns: 1
      topmargin: 0.02
      leftmargin: 0.25
      textsize: 14
      entrysep: 0.04
      entryheight: 0.008

  paths:

    EwkWhAllHad2016__n_jets:
      xmin: 4
      xmax: 10
      ymin: 1
      ymax: 1000000
      ndivisions: 10
      ylabel: Events
      xlabel: "Number of jets"
      plot tag: logy
      canvas:
        ndivisions: 10
    EwkWhAllHad2016__n_bjets:
      xmin: 0
      xmax: 6
      # ymin: 1
      # ymax: 1000000
      ymin: 0
      ymax: 1
      #ylabel: Events
      ylabel: Normalized to unity
      xlabel: "Number of b-tagged jets"
      # plot tag: logy
      canvas:
        ndivisions: 5
        logy: false
      normalize: unity
    # EwkWhAllHad2016__n_leptons:
    #   xmin: 0
    #   xmax: 6
    #   ymin: 1
    #   ymax: 1000000
    #   ylabel: Events
    #   xlabel: "Number of leptons"
    #   plot tag: logy
    #   canvas:
    #     ndivisions: 5

    # EwkWhAllHad2016__jet_1_pt:
    #   ylabel: Events
    #   xlabel: "p_{T,j1}"
    #   plot tag: logy
    # EwkWhAllHad2016__jet_2_pt:
    #   ylabel: Events
    #   xlabel: "p_{T,j2}"
    #   plot tag: logy
    # EwkWhAllHad2016__jet_3_pt:
    #   ylabel: Events
    #   xlabel: "p_{T,j3}"
    #   plot tag: logy
    # EwkWhAllHad2016__jet_4_pt:
    #   ylabel: Events
    #   xlabel: "p_{T,j4}"
    #   plot tag: logy
