---
# defines background groups for the cutflows
# wildcards for file patterns are allowed
# NOTE indentation matters
#
# ex. 
# backgrounds:
#   - name: dijets
#     files:
#       - *36102*.hists
#   - name: "t#bar{t}" 
#     files:
#       - *ttbar*.hists     
# 
groups:

  - name: "ttbar"
    type: background
    order: 0
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*ttbar*.hists

  - name: "singletop"
    type: background
    order: 1
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*singletop*.hists

  - name: "ttbar+X"
    type: background
    order: 2
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*topEW*.hists

  - name: "W+jets"
    type: background
    order: 3
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*W_sherpa_220*.hists

  - name: "Z+jets"
    type: background
    order: 4
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*Z_sherpa_220*.hists

  - name: "diboson"
    type: background
    order: 5
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*diboson*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.33-5-0-52-g169a7c2-mCTbb-MEV-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*342284*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.33-5-0-52-g169a7c2-mCTbb-MEV-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*342285*.hists

  - name: "dijet"
    type: background
    order: 6
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*dijet*.hists

  # signal samples

  - name: "(300, 0)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100001*300p0_0p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_300_0_detailed_cutflow_private.txt"

  - name: "(300, 50)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100002*300p0_50p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_300_50_detailed_cutflow_private.txt"

  - name: "(300, 100)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100003*300p0_100p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_300_100_detailed_cutflow_private.txt"

  - name: "(350, 0)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100004*350p0_0p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_350_0_detailed_cutflow_private.txt"

  - name: "(350, 50)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100005*350p0_50p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_350_50_detailed_cutflow_private.txt"

  - name: "(350, 100)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100006*350p0_100p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_350_100_detailed_cutflow_private.txt"

  - name: "(400, 0)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100007*400p0_0p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_400_0_detailed_cutflow_private.txt"

  - name: "(400, 50)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100008*400p0_50p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_400_50_detailed_cutflow_private.txt"

  - name: "(400, 100)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100009*400p0_100p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_400_100_detailed_cutflow_private.txt"

  - name: "(450, 0)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100010*450p0_0p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_450_0_detailed_cutflow_private.txt"

  - name: "(450, 50)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100011*450p0_50p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_450_50_detailed_cutflow_private.txt"

  - name: "(450, 100)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100012*450p0_100p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_450_100_detailed_cutflow_private.txt"

  - name: "(450, 150)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100013*450p0_150p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_450_150_detailed_cutflow_private.txt"

  - name: "(500, 0)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100014*500p0_0p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_500_0_detailed_cutflow_private.txt"

  - name: "(500, 50)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100015*500p0_50p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_500_50_detailed_cutflow_private.txt"

  - name: "(500, 100)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100016*500p0_100p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_500_100_detailed_cutflow_private.txt"

  - name: "(500, 150)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100017*500p0_150p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_500_150_detailed_cutflow_private.txt"

  - name: "(500, 200)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100018*500p0_200p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_500_200_detailed_cutflow_private.txt"

  - name: "(550, 0)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100019*550p0_0p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_550_0_detailed_cutflow_private.txt"

  - name: "(550, 50)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100020*550p0_50p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_550_50_detailed_cutflow_private.txt"

  - name: "(550, 100)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100021*550p0_100p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_550_100_detailed_cutflow_private.txt"

  - name: "(550, 150)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100022*550p0_150p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_550_150_detailed_cutflow_private.txt"

  - name: "(550, 200)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100023*550p0_200p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_550_200_detailed_cutflow_private.txt"

  - name: "(600, 0)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100024*600p0_0p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_600_0_detailed_cutflow_private.txt"

  - name: "(600, 50)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100025*600p0_50p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_600_50_detailed_cutflow_private.txt"

  - name: "(600, 100)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100026*600p0_100p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_600_100_detailed_cutflow_private.txt"

  - name: "(600, 150)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100027*600p0_150p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_600_150_detailed_cutflow_private.txt"

  - name: "(700, 0)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100028*700p0_0p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_700_0_detailed_cutflow_private.txt"

  - name: "(700, 50)"
    type: signal
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tag2.4.37-0-5-g6d1fba4-histograms/hf_cutflow_everycut_Wh_SR_CR_VR_October31_HT_incl_filter/*100029*700p0_50p0*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_October31/optimization_Wh_SR1_500_50_detailed_cutflow_private.txt"
 
# specify the path to each cutflow histogram
# one cutflow will be saved for each path
#

cutflows:
  paths:
    hists/all/cutflow:
      label: "All events"
      order: 0
    hists/default/cutflow:
      label: "Preselection"
      order: 1
    hists/optimization_Wh_SR1_nJetsEq4/cutflow:
      label: "$\\njet = 4$"
      order: 2
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200/cutflow:
      label: "\\Etmiss>200\\gev"
      order: 3
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto/cutflow:
      label: "$0L$"
      order: 4
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2/cutflow:
      label: "$\\nbjet = 2$"
      order: 5
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4/cutflow:
      label: "$\\dphimin>0.4$"
      order: 6
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900/cutflow:
      label: "$\\meffj>900\\gev$"
      order: 7
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140/cutflow:
      label: "$\\mTbmin>140\\gev$"
      order: 8
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140/cutflow:
      label: "$\\mctbb>140\\gev$"
      order: 9
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140_mbbG105L135/cutflow:
      label: "$105<\\mbb/\\gev<135$"
      order: 10
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140_mbbG105L135_mNonbbG75L90/cutflow:
      label: "$75<\\mnonbb/\\gev<90$"
      order: 11
