---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.65
  y: 0.65
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.77
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:
#  - name: data
#    files:
#      - TA01_MBJ17-18-19/hist-user.*.*.physics_Main.*.root
#    styles:
#      legendstyle: p
#      color: black
#    do not scale me: true

  - name: "410000 inclusive (gen_filt_ht < 600)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_cutflow_MctbbG160_mTbmin_Wh_optimization_May30_HT_incl_filter/user.jolsson.*410000*.merged.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  # - name: "407009 HT6c_1k (no filter)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_cutflow_MctbbG160_mTbmin_Wh_optimization_May30_HT_incl_filter/user.jolsson.*407009*.merged.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true
  #
  # - name: "407010 HT1k_1k5 (no filter)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_cutflow_MctbbG160_mTbmin_Wh_optimization_May30_HT_incl_filter/user.jolsson.*407010*.merged.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true
  #
  # - name: "407011 HT1k5 (no filter)"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_cutflow_MctbbG160_mTbmin_Wh_optimization_May30_HT_incl_filter/user.jolsson.*407011*.merged.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true

# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.65
        y: 0.61
        font: 43
        size: 15
        label: "#sqrt{s} = 13 TeV, L_{int} #approx 35 fb^{-1}"
    canvas:
      width: 800
      height: 600
      logy: true
    legend:
      numcolumns: 2
      topmargin: 0.02
      leftmargin: 0.02
      rightmargin: 0.02
      textsize: 18
      entrysep: 0.005
      entryheight: 0.01

  paths: 
    hists/default/gen_filt_ht
      xlabel: "gen_filt_ht"
      ylabel: "Events"
      # ymin: 0.1
      # ymax: 10000
      plot tag: logy
