---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.65
  y: 0.65
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.77
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:

  # - name: dijets
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*361022*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*361023*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*361024*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*361025*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*361026*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*361027*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*361028*.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true
  #
  # - name: "t#bar{t}"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*ttbar*.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true
  #
  # - name: "singletop"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*singletop*.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true
  #
  # - name: "t#bar{t}+V"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*topEW*.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true
  #
  # - name: "V+jets"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*W_sherpa*.hists
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Z_sherpa*.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true
  #
  # - name: "diboson"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*diboson*.hists
  #   styles:
  #     legendstyle: F
  #     fillstyle: solid
  #   stack it: true

  # - name: data
  #   files:
  #      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*period*.hists
  #   styles:
  #     legendstyle: p
  #     color: black
  #   do not scale me: true
  #   stack it: false

  - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_300p0_0p0*.hists
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false

  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_300p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 300, m_{#tilde{#chi^{0}_{1}}} = 100"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_300p0_100p0*.hists
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 350, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_350p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 350, m_{#tilde{#chi^{0}_{1}}} = 100"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_350p0_100p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 400, m_{#tilde{#chi^{0}_{1}}} = 0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_400p0_0p0*.hists
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 450, m_{#tilde{#chi^{0}_{1}}} = 50"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_450p0_50p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 0"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_500p0_0p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  # - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 500, m_{#tilde{#chi^{0}_{1}}} = 100"
  #   files:
  #     - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_500p0_100p0*.hists
  #   styles:
  #     legendstyle: L
  #     drawstyle: hist
  #     linewidth: 2
  #   stack it: false
  #
  - name: "m_{#tilde{#chi^{#pm}_{1}},#tilde{#chi^{0}_{2}}} = 600, m_{#tilde{#chi^{0}_{1}}} = 0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/histfitter/histograms/hf_main_variables_signal_August7/*Wh_600p0_0p0*.hists
    styles:
      legendstyle: L
      drawstyle: hist
      linewidth: 2
    stack it: false
  
# plots:
#     canvas:
#     legend:
#     texts:

plots:
  config:
    normalize: "unity"
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.65
        y: 0.61
        font: 43
        size: 15
        label: "#sqrt{s} = 13 TeV, L_{int} #approx 36 fb^{-1}"
    canvas:
      width: 800
      height: 600
      logy: False
    legend:
      numcolumns: 2
      topmargin: 0.02
      leftmargin: 0.02
      rightmargin: 0.02
      textsize: 18
      entrysep: 0.005
      entryheight: 0.01

  paths:

    ##### preselection 
 
    hists/preselection/cutflow:
      xlabel: "Cutflow"
      ylabel: "Normalized to unity"
      ymin: 0
      ymax: 2.0
    hists/preselection/jets_n:
      xmin: 0
      xmax: 10
      ymin: 0
      ymax: 0.8
      ylabel: Normalized to unity
      xlabel: "jet multiplicity"
    hists/preselection/bjets_n:
      xmin: 0
      xmax: 10
      ymin: 0
      ymax: 0.8
      ylabel: Normalized to unity
      xlabel: "b-jet multiplicity (77% eff)"
    hists/preselection/bjets_n_60:
      xmin: 0
      xmax: 10
      ymin: 0
      ymax: 0.8
      ylabel: Normalized to unity
      xlabel: "b-jet multiplicity (60% eff)"
    hists/preselection/bjets_n_70:
      xmin: 0
      xmax: 10
      ymin: 0
      ymax: 0.8
      ylabel: Normalized to unity
      xlabel: "b-jet multiplicity (70% eff)"
    hists/preselection/bjets_n_85:
      xmin: 0
      xmax: 10
      ymin: 0
      ymax: 0.8
      ylabel: Normalized to unity
      xlabel: "b-jet multiplicity (85% eff)"
    hists/preselection/pt_jet_1:
      xmin: 0
      xmax: 1000
      ymin: 0
      ymax: 0.20
      rebin: 4
      ylabel: Normalized to unity
      xlabel: "p_{T,1}"
    hists/preselection/pt_jet_2:
      xmin: 0
      xmax: 1000
      ymin: 0
      ymax: 0.40
      rebin: 4
      ylabel: Normalized to unity
      xlabel: "p_{T,2}"
    hists/preselection/pt_jet_3:
      xmin: 0
      xmax: 1000
      ymin: 0
      ymax: 0.6
      rebin: 4
      ylabel: Normalized to unity
      xlabel: "p_{T,3}"
    hists/preselection/pt_jet_4:
      xmin: 0
      xmax: 1000
      ymin: 0
      ymax: 0.8
      rebin: 4
      ylabel: Normalized to unity
      xlabel: "p_{T,4}"
    hists/preselection/dphi_min:
      xmin: 0
      xmax: 3.14
      ymin: 0
      ymax: 0.2
      ylabel: Normalized to unity
      xlabel: "min_{i=1-4} #Delta#Phi(jet_{i}, E_{T}^{miss})"
    hists/preselection/dphi_1jet:
      xmin: 0
      xmax: 3.14
      ymin: 0
      ymax: 0.2
      ylabel: Normalized to unity
      xlabel: "#Delta#Phi(jet_{1}, E_{T}^{miss})"
    hists/preselection/dphi_sum4jet:
      xmin: 0
      xmax: 3.14
      ymin: 0
      ymax: 0.8
      ylabel: Normalized to unity
      xlabel: "#Delta#Phi(di-boson, E_{T}^{miss})"
    hists/preselection/met:
      xmin: 200
      xmax: 700
      ymin: 0
      ymax: 0.10
      rebin: 2
      ylabel: Normalized to unity 
      xlabel: "E_{T}^{miss} [GeV]"
    hists/preselection/mTb_min:
      ymin: 0
      ymax: 0.15
      ymin: 0
      ymax: 0.2
      rebin: 4
      ylabel: Normalized to unity 
      xlabel: "M_{T}^{b,min}"
    hists/preselection/meff_4j:
      xmin: 0
      xmax: 2500
      ymin: 0
      ymax: 0.2
      rebin: 8
      ylabel: Normalized to unity
      xlabel: "M_{eff}^{4j}"
    hists/preselection/mT_4j:
      xmin: 0
      xmax: 2500
      ymin: 0
      ymax: 0.2
      rebin: 8
      ylabel: Normalized to unity
      xlabel: "M_{T}^{4j}"
    hists/preselection/minv_2j:
      xmin: 0
      xmax: 2500
      ymin: 0
      ymax: 0.2
      rebin: 8
      ylabel: Normalized to unity
      xlabel: "M^{2j}"
    hists/preselection/mT_2j:
      xmin: 0
      xmax: 2500
      ymin: 0
      ymax: 0.2
      rebin: 8
      ylabel: Normalized to unity
      xlabel: "M_{T}^{2j}"
    hists/preselection/minv_bb:
      xmin: 80
      xmax: 150
      ymin: 0
      ymax: 0.2
      rebin: 1
      ylabel: Normalized to unity
      xlabel: "M^{bb}"
    hists/preselection/mT_bb:
      ymin: 0
      ymax: 0.2
      rebin: 8
      ylabel: Normalized to unity
      xlabel: "M_{T}^{bb}"
    hists/preselection/mct_bb:
      xmin: 50
      xmax: 600
      ymin: 0
      ymax: 0.05
      rebin: 2
      ylabel: Normalized to unity
      xlabel: "M_{CT}^{bb}"
    hists/preselection/minv_non_bb:
      xmin: 50
      xmax: 110
      ymin: 0
      ymax: 0.2
      rebin: 1
      ylabel: Normalized to unity
      xlabel: "M^{non-bb}"
    hists/preselection/mT_non_bb:
      ymin: 0
      ymax: 0.2
      rebin: 8
      ylabel: Normalized to unity
      xlabel: "M_{T}^{non-bb}"
    hists/preselection/mct_non_bb:
      xmin: 50
      xmax: 600
      ymin: 0
      ymax: 0.1
      rebin: 2
      ylabel: Normalized to unity
      xlabel: "M_{CT}^{non-bb}"

    ##### leptonveto_nBJetsEq2_dphiMinG0p4 
 
    hists/leptonveto_nBJetsEq2_dphiMinG0p4/minv_bb:
      xmin: 80
      xmax: 150
      ymin: 0
      ymax: 0.2
      rebin: 1
      ylabel: Normalized to unity
      xlabel: "M^{bb}"
    hists/leptonveto_nBJetsEq2_dphiMinG0p4/minv_non_bb:
      xmin: 50
      xmax: 110
      ymin: 0
      ymax: 0.2
      rebin: 1
      ylabel: Normalized to unity
      xlabel: "M^{non-bb}"

    ##### leptonveto_nBJetsEq2_dphiMinG0p4_dphiSum4jetG2p6_meffG700 
 
    hists/leptonveto_nBJetsEq2_dphiMinG0p4_dphiSum4jetG2p6_meffG700/minv_bb:
      xmin: 80
      xmax: 150
      ymin: 0
      ymax: 0.2
      rebin: 1
      ylabel: Normalized to unity
      xlabel: "M^{bb}"
    hists/leptonveto_nBJetsEq2_dphiMinG0p4_dphiSum4jetG2p6_meffG700/minv_non_bb:
      xmin: 50
      xmax: 110
      ymin: 0
      ymax: 0.2
      rebin: 1
      ylabel: Normalized to unity
      xlabel: "M^{non-bb}"
