---
# we can have text properties which specify what text to draw (think atlas, prelim, internal)
# NOTE indentation matters
#   # this one pulls in all of the reference that's pre-defined
#   texts:
#     - *atlas
#   # this one merges the &internal with the current hash so everything but the label is the same
#   texts:
#     - label: preliminary
#       <<: *internal
#   texts:
#     - x: <position>
#       y: <position>
#       font: <number> (for SetTextFont(...))
#       size: <number> (for SetTextSize(...))
#       label: <string> (what to actually say)

atlas: &atlas
  x: 0.25
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.36
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal

labeloptions: &labeloptions
  xtitleoffset: 1.4
  ytitleoffset: 1.4
  xtitlesize: 0.05
  ytitlesize: 0.05
  xlabelsize: 0.05
  ylabelsize: 0.05

# top level defines the label / grouping
# second level is a list of files under that group, one can also specify a wildcard to match files so they all get grouped
# third level specifies extra information for a given file such as plots to ignore
# groups:
#   - name: <group name>
#     files:
#       - <a file path or a file pattern to match a set of files>
#     styles:
#       <name of style>: <value for style>
#   - name: <group name>
#     files: [file1, file2, ...]
#     styles: {style1: val1, style2: val2, ...}

# styles are set on all hists associated with that group
# styles:
#   - drawstyle (passed into Draw(...), think 'same' or 'hist')
#   - legendstyle (passed into Legend(...), think 'F')
#   - markercolor (also set with 'color')
#   - markerstyle
#   - markersize
#   - fillcolor (also set with 'color')
#   - fillstyle
#   - linecolor (also set with 'color')
#   - linestyle
#   - linewidth
#   - color (sets markercolor, fillcolor, linecolor)

groups:

  - name: "Single-top Wt, inclusive (410013, 410014)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-filter-check/hf_main_variables_dataMC_December4_HT_incl_filter_check/*410013*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-filter-check/hf_main_variables_dataMC_December4_HT_incl_filter_check/*410014*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

  - name: "Single-top Wt, HT>500 GeV (407018, 407020)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-filter-check/hf_main_variables_dataMC_December4_HT_incl_filter_check/*407018*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-filter-check/hf_main_variables_dataMC_December4_HT_incl_filter_check/*407020*.hists
    styles:
      legendstyle: F
      fillstyle: solid
    stack it: true

# plots:
#   config:  # here we set global configurations that are applied uniformly such as...
#     canvas:
#     legend:
#     texts:

plots:
  config:
    texts:
      - *atlas
      - *internal
      - &topline
        x: 0.25
        y: 0.84
        font: 43
        size: 20
        label: "36.1 fb^{-1}"
      -
        x: 0.25
        y: 0.80
        font: 43
        size: 20
        label: "0L, #geq4j, #geq2b, E_{T}^{miss}>200 GeV, #Delta#phi^{4j}_{min}>0.4"
    canvas:
      width: 800
      height: 600
      logy: true
      ndivisions: 505
    legend:
      numcolumns: 1
      topmargin: 0.18
      leftmargin: 0.02
      textsize: 18
      entrysep: 0.050
      entryheight: 0.007

  paths:

    ##### leptonveto_nJetsGeq4_nBJetsGeq2_metG200_dphiMinG0p4

    hists/leptonveto_nJetsGeq4_nBJetsGeq2_metG200_dphiMinG0p4/met:
      xmin: 0
      xmax: 2000
      ymin: 1
      ymax: 10000
      rebin: 1
      ylabel: Events
      xlabel: "E_{T}^{miss} [GeV]"
      plot tag: logy

    hists/leptonveto_nJetsGeq4_nBJetsGeq2_metG200_dphiMinG0p4/meff_4j:
      xmin: 0
      xmax: 2000
      ymin: 0.01
      ymax: 10000
      rebin: 1
      ylabel: Events
      xlabel: "m_{eff}^{4j} [GeV]"
      plot tag: logy

    hists/leptonveto_nJetsGeq4_nBJetsGeq2_metG200_dphiMinG0p4/gen_filt_met:
      xmin: 0
      xmax: 2000
      ymin: 1
      ymax: 10000
      rebin: 1
      ylabel: Events
      xlabel: "gen_filt_met [GeV]"
      plot tag: logy

    hists/leptonveto_nJetsGeq4_nBJetsGeq2_metG200_dphiMinG0p4/gen_filt_ht:
      xmin: 0
      xmax: 2000
      ymin: 1
      ymax: 10000
      rebin: 1
      ylabel: Events
      xlabel: "gen_filt_ht [GeV]"
      plot tag: logy
