---
# defines background groups for the cutflows
# wildcards for file patterns are allowed
# NOTE indentation matters
#
# ex. 
# backgrounds:
#   - name: dijets
#     files:
#       - *36102*.hists
#   - name: "t#bar{t}" 
#     files:
#       - *ttbar*.hists     
# 
backgrounds:

  - name: "dijet" 
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*dijet*.hists

  - name: "diboson"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*diboson*.hists

  - name: "ttbar"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*ttbar*.hists

  - name: "singletop"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*singletop*.hists

  - name: "ttbar+X"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*topEW*.hists

  - name: "W+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*W_sherpa_220*.hists

  - name: "Z+jets"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*Z_sherpa_220*.hists

# defined analogously for signal samples
# one group per signal sample is required
signals:

  - name: "(350, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394329*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_350_0_detailed_cutflow.txt"

  - name: "(350, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394330*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_350_50_detailed_cutflow.txt"

  - name: "(400, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394331*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_400_0_detailed_cutflow.txt"

  - name: "(400, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394332*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_400_50_detailed_cutflow.txt"

  - name: "(400, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394333*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_400_0_detailed_cutflow.txt"

  - name: "(450, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394334*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_450_0_detailed_cutflow.txt"

  - name: "(450, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394335*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_450_50_detailed_cutflow.txt"

  - name: "(450, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394336*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_450_100_detailed_cutflow.txt"

  - name: "(450, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394337*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_450_150_detailed_cutflow.txt"

  - name: "(500, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394338*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_500_0_detailed_cutflow.txt"

  - name: "(500, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394339*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_500_50_detailed_cutflow.txt"

  - name: "(500, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394340*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_500_100_detailed_cutflow.txt"

  - name: "(500, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394341*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_500_150_detailed_cutflow.txt"

  - name: "(500, 175)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394342*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_500_175_detailed_cutflow.txt"

  - name: "(550, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394343*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_550_0_detailed_cutflow.txt"

  - name: "(550, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394344*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_550_50_detailed_cutflow.txt"

  - name: "(550, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394345*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_550_100_detailed_cutflow.txt"

  - name: "(550, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394346*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_550_150_detailed_cutflow.txt"

  - name: "(550, 175)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394347*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_550_175_detailed_cutflow.txt"

  - name: "(600, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394348*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_600_0_detailed_cutflow.txt"

  - name: "(600, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394349*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_600_50_detailed_cutflow.txt"

  - name: "(600, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394350*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_600_100_detailed_cutflow.txt"

  - name: "(600, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394351*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_600_150_detailed_cutflow.txt"

  - name: "(600, 175)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394352*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_600_175_detailed_cutflow.txt"

  - name: "(650, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394353*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_650_0_detailed_cutflow.txt"

  - name: "(650, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394354*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_650_50_detailed_cutflow.txt"

  - name: "(650, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394355*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_650_100_detailed_cutflow.txt"

  - name: "(650, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394356*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_650_150_detailed_cutflow.txt"

  - name: "(700, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394357*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_700_0_detailed_cutflow.txt"

  - name: "(700, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394358*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_700_50_detailed_cutflow.txt"

  - name: "(550, 200)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394751*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_550_200_detailed_cutflow.txt"
  - name: "(550, 250)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394752*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_550_250_detailed_cutflow.txt"
  - name: "(600, 200)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394753*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_600_200_detailed_cutflow.txt"
  - name: "(600, 250)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394754*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_600_250_detailed_cutflow.txt"
  - name: "(650, 175)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394755*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_650_175_detailed_cutflow.txt"
  - name: "(650, 200)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394756*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_650_200_detailed_cutflow.txt"
  - name: "(650, 250)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394757*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_650_250_detailed_cutflow.txt"
  - name: "(700, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394758*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_700_100_detailed_cutflow.txt"
  - name: "(700, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394759*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_700_150_detailed_cutflow.txt"
  - name: "(700, 175)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394760*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_700_175_detailed_cutflow.txt"
  - name: "(700, 200)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394761*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_700_200_detailed_cutflow.txt"
  - name: "(750, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394762*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_750_0_detailed_cutflow.txt"
  - name: "(750, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394763*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_750_50_detailed_cutflow.txt"
  - name: "(750, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394764*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_750_100_detailed_cutflow.txt"
  - name: "(750, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394765*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_750_150_detailed_cutflow.txt"
  - name: "(800, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394766*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_800_0_detailed_cutflow.txt"
  - name: "(800, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394767*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_800_50_detailed_cutflow.txt"
  - name: "(800, 100)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394768*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_800_100_detailed_cutflow.txt"
  - name: "(800, 150)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394769*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_800_150_detailed_cutflow.txt"
  - name: "(850, 0)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394770*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_850_0_detailed_cutflow.txt"
  - name: "(850, 50)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*394771*.hists
    outfile: "cutflow_resolved/cutflow_everycut_Wh_SR1_November16/optimization_Wh_SR1_850_50_detailed_cutflow.txt"

 
# specify the path to each cutflow histogram
# one cutflow will be saved for each path
#

cutflows:
  paths:
    hists/all/cutflow:
      label: "All events"
      order: 0
    hists/default/cutflow:
      label: "Preselection"
      order: 1
    hists/optimization_Wh_SR1_nJetsEq4/cutflow:
      label: "$\\njet = 4$"
      order: 2
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200/cutflow:
      label: "\\Etmiss>200\\gev"
      order: 3
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto/cutflow:
      label: "$0L$"
      order: 4
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2/cutflow:
      label: "$\\nbjet = 2$"
      order: 5
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4/cutflow:
      label: "$\\dphimin>0.4$"
      order: 6
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900/cutflow:
      label: "$\\meffj>900\\gev$"
      order: 7
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140/cutflow:
      label: "$\\mTbmin>140\\gev$"
      order: 8
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140/cutflow:
      label: "$\\mctbb>140\\gev$"
      order: 9
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140_mbbG105L135/cutflow:
      label: "$105<\\mbb/\\gev<135$"
      order: 10
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140_mbbG105L135_mNonbbG75L90/cutflow:
      label: "$75<\\mnonbb/\\gev<90$"
      order: 11
