---
# defines samples groups for the cutflows
# wildcards for file patterns are allowed
# NOTE indentation matters
#
# ex. 
# samples:
#   - name: dijets
#     files:
#       - *36102*.hists
#   - name: "t#bar{t}" 
#     files:
#       - *ttbar*.hists     
# 
groups:

  - name: "\\srone cuts: \\ttbar (HT-filter)"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*ttbar*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_ttbar_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbar (inclusive, 410000) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*410000*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_ttbar_410000_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbar (600<HT<1000, 407009) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*407009*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_ttbar_407009_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbar (1000<HT<1500, 407010) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*407010*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_ttbar_407010_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbar (HT>1500, 407011) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*407011*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_ttbar_407011_detailed_cutflow.txt"

  - name: "\\srone cuts: single-top"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*singletop*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_singletop_detailed_cutflow.txt"

  - name: "\\srone cuts: single-top (Wt anti-top, HT > 500 GeV, 407020) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*407020*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_singletop_407020_detailed_cutflow.txt"

  - name: "\\srone cuts: single-top (Wt top, inclusive, 410013) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*410013*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_singletop_410013_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbarX"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*topEW*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_topEW_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbarX (ttH semilep, 341270) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*341270*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_topEW_341270_detailed_cutflow.txt"

  - name: "\\srone cuts: \\ttbarX (ttZnnqq Np0, 410073) -- after"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*410073*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_topEW_410073_detailed_cutflow.txt"

  - name: "\\srone cuts: ttH"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*341177*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*341270*.hists
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*341271*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_ttH_detailed_cutflow.txt"

  - name: "\\srone cuts: \\Wjets, Sherpa 2.2.0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*W_sherpa_220*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_W_sherpa_220_detailed_cutflow.txt"

  - name: "\\srone cuts: \\Zjets, Sherpa 2.2.0"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*Z_sherpa_220*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_Z_sherpa_220_detailed_cutflow.txt"

  - name: "\\srone cuts: \\Wjets, Sherpa 2.2.1"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*W_sherpa_221*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_W_sherpa_221_detailed_cutflow.txt"

  - name: "\\srone cuts: \\Zjets, Sherpa 2.2.1"
    files:
      - /Users/joakim/ewk/ewk_mbj_ntuples/tagEWKqqbb.2.4.37-0-histograms-noloosefilter/hf_cutflow_everycut_Wh_SR_CR_VR_November16_HT_incl_filter/*Z_sherpa_221*.hists
    outfile: "cutflow_resolved/bkgd_detailed_cutflows_November16/bkgd_SR1_Z_sherpa_221_detailed_cutflow.txt"

# specify the path to each cutflow histogram
# one cutflow will be saved for each path
#

cutflows:
  paths:
    hists/all/cutflow:
      label: "All events"
      order: 0
    hists/default/cutflow:
      label: "Preselection"
      order: 1
    hists/optimization_Wh_SR1_nJetsEq4/cutflow:
      label: "$\\njet = 4$"
      order: 2
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200/cutflow:
      label: "\\Etmiss>200\\gev"
      order: 3
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto/cutflow:
      label: "$0L$"
      order: 4
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2/cutflow:
      label: "$\\nbjet = 2$"
      order: 5
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4/cutflow:
      label: "$\\dphimin>0.4$"
      order: 6
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900/cutflow:
      label: "$\\meffj>900\\gev$"
      order: 7
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140/cutflow:
      label: "$\\mTbmin>140\\gev$"
      order: 8
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140/cutflow:
      label: "$\\mctbb>140\\gev$"
      order: 9
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140_mbbG105L135/cutflow:
      label: "$105<\\mbb/\\gev<135$"
      order: 10
    hists/optimization_Wh_SR1_nJetsEq4_passMET_metG200_leptonveto_nBJetsEq2_dphiMinG0p4_meffG900_mTbminG140_mCTbbG140_mbbG105L135_mNonbbG75L90/cutflow:
      label: "$75<\\mnonbb/\\gev<90$"
      order: 11
